apiVersion: v2
appVersion: 1.0.0
description: A container-aware Django application chart
keywords:
- django
- python
- web
maintainers:
- name: platform-team
name: django-app
type: application
version: 0.1.3
