apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-backup-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /backup/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - amir-thinkbook-15-g2-itl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: crypto-exchange
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: pg-dump
              image: postgres:18.6
              envFrom:
                - configMapRef:
                    name: app-config
                - secretRef:
                    name: app-secret
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: DATABASE_PASSWORD
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: DATABASE_NAME
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: DATABASE_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: DATABASE_PASSWORD
              command:
                - "sh"
                - "-c"
                - |
                  set -e
                  TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
                  FILE="/backups/${DATABASE_NAME}_${TIMESTAMP}.dump"
                  echo "Starting backup: $FILE"
                  pg_dump -h "$DATABASE_HOST" -p "$DATABASE_PORT" -U "$POSTGRES_USER" -Ft -d "$POSTGRES_DB" -f "$FILE"
                  echo "Verifying dump integrity..."
                  pg_restore --list "$FILE" > /dev/null
                  echo "Backup is OK: $FILE"
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "2000m"
                  memory: "4096Mi"
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-backup-pvc