apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  EXTERNAL_IP_BIND: "0.0.0.0"           # Ip interfaces to serve the app on.
  EXTERNAL_PORT: "8000"                 # The port number of application.
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  ALLOWED_HOSTS: "dex.local"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  API_KEY: "REPLACE_WITH_REAL_API_KEY"  # API-KEY mentioned in server's documents.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;
        location /static/ {
          alias /usr/share/nginx/html/static/;
        }
      }
    }